name: 'Branch to Docker Tag Name'
description: 'Converts a branch to a valid docker tag name'
inputs:
  branch:
    description: 'The branch to clean'
    required: true
  prefix:
    description: 'A prefix to remove'
    required: false
    default: ''
  main:
    description: 'The name of your main branch'
    required: false
    default: 'main'

outputs:
  image-name:
    description: 'Valid docker tag name'

branding:
  icon: 'activity'
  color: 'green'

runs:
  using: 'node16'
  main: 'index.js'


